export const GET_CANDIDATES = 'GET_CANDIDATES';
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_LOADING='SET_LOADING';
export const CANDIDATE_ERROR='CANDIDATE_ERROR';